FROM node:alpine as back-build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build
RUN yarn --production && yarn cache clean

FROM node:alpine
WORKDIR /app
COPY --from=back-build /app /app
EXPOSE 80
CMD ["yarn","start"]
