version: "3.7"
services:
  postgres:
    container_name: ttis-postgres-dev
    image: postgres:alpine
    environment:
      POSTGRES_DB: ttis
      POSTGRES_USER: ttis
      POSTGRES_PASSWORD: test
    volumes:
      - postgresql-vol:/var/lib/postgresql/data
      - socket-vol:/var/run/postgresql
    ports:
      - 5432:5432
  caddy:
    container_name: ttis-caddy-dev
    image: caddy:alpine
    ports:
      - 80:80
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
  redis:
    container_name: ttis-redis-dev
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-vol:/data
volumes:
  postgresql-vol:
  redis-vol:
  socket-vol:
  