name: BuildTest(push)
on:
  push:
jobs:
  frontend:
    name: frontend test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ttis-front:Cache node modules(yarn.lock)
        id: cache
        uses: actions/cache@v1
        with:
          path: ttis-front/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('ttis-front/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}
      - name: ttis-front:package-install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --cwd ttis-front
      - name: ttis-front:build
        run: yarn --cwd ttis-front build
  backend:
    name: backend test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ttis-back:Cache node modules(yarn.lock)
        id: ttis-back-cache
        uses: actions/cache@v1
        with:
          path: ttis-back/node_modules
          key: ${{ runner.OS }}-build-back-${{ hashFiles('ttis-back/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}-
      - name: ttis-back:package-install
        if: steps.ttis-back-cache.outputs.cache-hit != 'true'
        run: yarn --cwd ttis-back
      - name: ttis-back:build
        run: yarn --cwd ttis-back build
      - name: ttis-back:test
        run: yarn --cwd ttis-back test
  deploy:
    name: Docker deploy
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - uses: actions/checkout@v2
      - name: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_KEY" > .ssh_key
          chmod 0600 ssh_key
          ssh -o StrictHostKeyChecking=no -i .ssh_key $SSH_USER -L 2375:localhost:2375 -N -f
      - name: docker build
        run: docker-compose -f docker/docker-compose.yml build --parallel
      - name: docker deploy
        run: docker save ttis-redis ttis-nginx ttis-front ttis-back | docker -H localhost load
      - name: docker start
        run: docker-compose -H localhost:2375 -f docker/docker-compose.yml up -d
